workflows:
  build-android:
    name: Build Android (assembleDebug)
    instance_type: linux
    max_build_duration: 60
    scripts:
      - name: Prepare
        script: |
          set -e
          echo "Preparing build environment..."
          # make gradlew executable if exists
          if [ -f ./gradlew ]; then
            chmod +x ./gradlew || true
          fi
      - name: Build (assembleDebug)
        script: |
          set -e
          echo "Starting build: try wrapper first"
          if [ -x ./gradlew ]; then
            ./gradlew assembleDebug --no-daemon
          else
            echo "gradlew not found or not executable. Trying system gradle..."
            gradle assembleDebug --no-daemon
          fi
    artifacts:
      - app/build/outputs/**/*.apk
